const oxc = require('oxc-transform')
const fs = require('fs')
const glob = require('glob')

const removeDeclarations = () => {
  const dtsPaths = glob.sync('./**/*.d.ts*')

  dtsPaths.forEach(dtsPath => {
    fs.unlinkSync(dtsPath)
  })
}

// to align with the format of sourcemaps generated by tsc
const formatMap = (map, dtsPath) => {
  const formattedMap = {...map}
  const dtsFileName = dtsPath.split('/').pop() || dtsPath

  formattedMap.file = dtsFileName
  delete formattedMap.sourcesContent

  return JSON.stringify(formattedMap)
}

const generateDeclarations = (directory, extension) => {
  const tsPaths = glob.sync(`${directory}/**/*.ts`)

  tsPaths.forEach(tsPath => {
    const fileName = tsPath.split('/').pop()
    const dtsPath = tsPath.replace('.ts', extension)
    const dtsMapPath = tsPath.replace('.ts', `${extension}.map`)
    const {code, map} = oxc.isolatedDeclaration(fileName, fs.readFileSync(tsPath, 'utf8'))

    fs.writeFileSync(dtsPath, code)
    fs.writeFileSync(dtsMapPath, formatMap(map, dtsPath))
  })
}

removeDeclarations()
generateDeclarations('dts', '.d.ts')
generateDeclarations('gen-dts', '.gen.d.ts')
